### ISSUE TITLE
Demuxer expects whole file to be available when probing

### ISSUE THREAD

**Issue by Pheo-Player** [audiocogs/mp3.js#12]
See https://github.com/fsbdev/aurora-websocket/issues/1

I investigated and found the UnderflowError's cause to be in `MP3Demuxer.probe` (l. 138), where the stream tries to `advance` and can't due to the data not having been streamed yet.

FLAC.js meanwhile works, because all its `probe` function does is peek a string at the beginning of the file. So I googled around for a bit checking if I can find similar logic for MP3s, and found this answer:
http://stackoverflow.com/a/7302482/3090225
and replaced the `probe` function with the following code:

``` js
const sigID3 = 0x494433;
const sigNoID3 = 0xfffb;
this.probe = function(stream) {
    var off = stream.offset; // Not entirely sure if this needs to be here, but it already was

    return stream.peekUInt16(off) == sigNoID3 ||
        stream.peekUInt24(off) == sigID3;
};
```

which got my MP3 file to play, even though I have 9 errors being thrown now:

![screen shot 2014-09-30 at 09 06 56](https://cloud.githubusercontent.com/assets/8202381/4454486/69586b20-4870-11e4-80ff-fa0a86254b34.png)

But the file still played from start to end without further errors or audible glitches.

**Comment by ChanYiChih** [comment]
@devongovett 

Hi devongovett:

I tried to parse AAC - ADTS format into ADTS packets.
It works if I feed packets one by one to aurora quickly.
But if I feed packets slowly, like maybe 50 ms delayed, it would be silence after a few seconds.
And there is no error shown by aurora.js or aac.js.

Would you please tell me why, and how to fix it.
Thanks a lot.

below is my aac - adts raw data
https://www.dropbox.com/s/cwmycw4qglbzhya/adts.txt?dl=0

below is my code, if you change 50 to 10, it works like a charm
but if you use 50 as timeout value, it would play several seconds but play no sound afterwards.

var adts = [[]]...; // you can download it from above link
var index = 0;
var MySource = AV.EventEmitter.extend({
    start: function() {
        var source = this;

        setTimeout(function ZZZ() {
            var abData = new AV.Buffer(new Uint8Array(adts[index]));
            source.emit('data', abData);
            index += 1;
            if (index < length) {
                setTimeout(ZZZ, 50);
            } else {
                source.emit('end');
            }
        }, 50);
    },

    pause: function() {
        console.error('pause');
    },

    reset: function() {
        console.error('reset');
    }
});

// create a source, asset and player
var source = new MySource();
var asset = new AV.Asset(source);
var player = new AV.Player(asset);
player.play();
