### ISSUE TITLE
Standalone use

### ISSUE THREAD

**Issue by dy** [audiocogs/mp3.js#21]
Hi @devongovett!

We are running @audiojs org and recently came up with [audio-decode](https://github.com/audiojs/audio-decode) component to decode audio data in node.
We would like to include decoders for formats other than `wav` and aurora looks great for that, but it seems that aurora is a bit too big dependency for us as we tend to keep things atomic.
I would really like to give a try to mp3 and other codecs, but I did not manage to find any docs how to use them aside from aurora.

So I wonder if there is any way to use _mp3_ as a standalone package, or we should use it within aurora?

Appreciate any help or references.

**Comment by devongovett** [comment]
aurora.js is a hard dependency of mp3.js. mp3.js is a plugin, and in fact extends from and uses many classes in the aurora framework.

Either way, aurora itself is quite small. mp3.js is much larger.
